version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli@11.0.2
  pre_build:
    commands:
      - npm install 
  build:
    commands:
      - ng build --prod
artifacts:
  base-directory: dist/mk-tictactoe-ui
  files:
    - '**/*'